import { Thermometer, Eye, Fish, Waves, Star, Anchor } from "lucide-react";
import React from "react";

export const DESTINATIONS = [
  {
    id: "providencia",
    name: "Providencia",
    taglineEs: "El Paraíso Virgen del Caribe",
    taglineEn: "The Untouched Caribbean Paradise",
    descEs: "Tercer arrecife de barrera más grande del mundo. Reserva de Biosfera UNESCO con 850+ especies marinas.",
    descEn: "Third largest barrier reef in the world. UNESCO Biosphere Reserve with 850+ marine species.",
    region: "Caribe",
    regionEn: "Caribbean",
    img: "/images/img-94034723.jpg",
    href: "/destinos/providencia",
    stats: [
      { icon: <Thermometer size={13} />, label: "27°C" },
      { icon: <Eye size={13} />, label: "20–30m vis." },
      { icon: <Fish size={13} />, label: "850+ sp." },
    ],
    levelEs: "Intermedio",
    levelEn: "Intermediate",
    badge: "UNESCO",
    accentColor: "#48cae4",
  },
  {
    id: "isla-fuerte",
    name: "Isla Fuerte",
    taglineEs: "Coral Virgen & Aguas Cristalinas",
    taglineEn: "Pristine Coral & Crystal Waters",
    descEs: "Una isla sin carros ni ruido. Corales intactos, langosta fresca y una comunidad que vive del mar.",
    descEn: "An island without cars or noise. Intact corals, fresh lobster, and a community living from the sea.",
    region: "Caribe",
    regionEn: "Caribbean",
    img: "/images/img-828314b5.jpg",
    href: "/destinos/isla-fuerte",
    stats: [
      { icon: <Thermometer size={13} />, label: "28°C" },
      { icon: <Eye size={13} />, label: "15–25m vis." },
      { icon: <Waves size={13} />, label: "Arrecife" },
    ],
    levelEs: "Principiante",
    levelEn: "Beginner",
    badge: null,
    accentColor: "#90e0ef",
  },
  {
    id: "malpelo",
    name: "Malpelo",
    taglineEs: "El Galápagos Colombiano",
    taglineEn: "The Colombian Galápagos",
    descEs: "Patrimonio de la Humanidad UNESCO. Cientos de tiburones martillo, mantas gigantes y una biodiversidad inigualable.",
    descEn: "UNESCO World Heritage Site. Hundreds of hammerhead sharks, giant mantas, and unmatched biodiversity.",
    region: "Pacífico",
    regionEn: "Pacific",
    img: "/malpelo-tiburones.jpg",
    href: "/destinos/malpelo",
    stats: [
      { icon: <Thermometer size={13} />, label: "24–28°C" },
      { icon: <Eye size={13} />, label: "10–30m vis." },
      { icon: <Star size={13} />, label: "Avanzado" },
    ],
    levelEs: "Avanzado",
    levelEn: "Advanced",
    badge: "UNESCO",
    accentColor: "#0096c7",
  },
  {
    id: "gorgona",
    name: "Gorgona",
    taglineEs: "Ballenas, Tiburones & Selva",
    taglineEn: "Whales, Sharks & Jungle",
    descEs: "Isla de reserva natural en el Pacífico. Temporada de ballenas jorobadas (jul–oct). Ecosistema único en Colombia.",
    descEn: "Pacific nature reserve island. Humpback whale season (Jul–Oct). Unique ecosystem in Colombia.",
    region: "Pacífico",
    regionEn: "Pacific",
    img: "/images/img-3a729866.jpg",
    href: null,
    stats: [
      { icon: <Thermometer size={13} />, label: "26°C" },
      { icon: <Fish size={13} />, label: "Ballenas" },
      { icon: <Anchor size={13} />, label: "Liveaboard" },
    ],
    levelEs: "Intermedio",
    levelEn: "Intermediate",
    badge: null,
    accentColor: "#0077b6",
  },
  {
    id: "taganga",
    name: "Taganga",
    taglineEs: "El Punto de Inicio Perfecto",
    taglineEn: "The Perfect Starting Point",
    descEs: "Nuestra base de operaciones. Arrecifes accesibles, agua cálida y el mejor punto de partida para certificarte con PADI.",
    descEn: "Our operations base. Accessible reefs, warm water and the best starting point to get PADI certified.",
    region: "Caribe",
    regionEn: "Caribbean",
    img: "/Morena.jpg",
    href: "/destinos/santa-marta",
    stats: [
      { icon: <Thermometer size={13} />, label: "29°C" },
      { icon: <Eye size={13} />, label: "10–20m vis." },
      { icon: <Waves size={13} />, label: "PADI Base" },
    ],
    levelEs: "Todos los niveles",
    levelEn: "All levels",
    badge: null,
    accentColor: "#48cae4",
  },
];
